# Generated by Django 5.0.2 on 2024-08-16 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utenti',
            name='pwd',
        ),
        migrations.RemoveField(
            model_name='utenti',
            name='username',
        ),
        migrations.AddField(
            model_name='utenti',
            name='user',
            field=models.OneToOneField(default=20, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
