# Generated by Django 5.0.2 on 2024-08-16 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0002_remove_utenti_pwd_remove_utenti_username_utenti_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='utenti',
            name='type',
            field=models.CharField(choices=[('Venditore', 'venditore'), ('Compratore', 'compratore')], default='Venditore', max_length=10),
        ),
    ]
