# Generated by Django 5.0.2 on 2024-08-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0003_utenti_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='oggetti',
            name='data',
            field=models.DateField(default="2024-08-24"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='oggetti',
            name='categoria',
            field=models.CharField(choices=[('Tech', 'tech'), ('Cucina', 'cucina'), ('Altro', 'altro')], default='Tech', max_length=10),
        ),
    ]
