# Generated by Django 5.0.2 on 2024-08-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0005_remove_oggetti_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oggetti',
            name='categoria',
            field=models.CharField(max_length=255),
        ),
    ]
