# Generated by Django 5.0.2 on 2024-08-27 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0007_oggetti_data_alter_oggetti_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oggetti',
            name='data',
        ),
    ]
