# Generated by Django 5.0.2 on 2024-08-27 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0008_remove_oggetti_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='oggetti',
            name='nome',
            field=models.CharField(default=4, max_length=255),
            preserve_default=False,
        ),
    ]
