# Generated by Django 5.0.2 on 2024-08-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0009_oggetti_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='oggetti',
            name='data',
            field=models.DateField(default='2024-08-25'),
        ),
    ]
