# Generated by Django 5.0.2 on 2024-08-27 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0010_oggetti_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oggetti',
            name='data',
            field=models.DateField(),
        ),
    ]
