# Generated by Django 5.0.2 on 2024-08-27 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0011_alter_oggetti_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='oggetti',
            name='image',
            field=models.ImageField(default=3, upload_to='images/'),
            preserve_default=False,
        ),
    ]
