# Generated by Django 5.0.2 on 2024-08-29 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0014_acquisti_stato'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('data_offerta', models.DateTimeField(auto_now_add=True)),
                ('oggetto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerte', to='eco.oggetti')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
