# Generated by Django 5.0.2 on 2024-08-29 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0018_alter_acquisti_compratore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acquisti',
            name='compratore',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='acquisti',
            name='venditore',
            field=models.CharField(max_length=255),
        ),
    ]
