# Generated by Django 5.0.2 on 2024-08-30 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0019_alter_acquisti_compratore_alter_acquisti_venditore'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifiche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utente', models.CharField(max_length=255)),
                ('messaggio', models.CharField(max_length=255)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('oggetto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifica', to='eco.oggetti')),
            ],
        ),
    ]
