# Generated by Django 5.0.2 on 2024-08-31 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0021_remove_utenti_type_utenti_immagine_profilo'),
    ]

    operations = [
        migrations.AddField(
            model_name='utenti',
            name='best_buyer',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='utenti',
            name='best_seller',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
