# Generated by Django 5.0.2 on 2024-09-04 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0024_alter_oggetti_categoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Messaggio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testo', models.TextField()),
                ('data_invio', models.DateTimeField(auto_now_add=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messaggi_ricevuti', to=settings.AUTH_USER_MODEL)),
                ('mittente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messaggi_inviati', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
